GNFSRS.WebUI/Controllers/AfterReportController.cs
using System;
using System.Collections.Generic;
using System.Data;
using PagedList;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GNFSRS.Domain.Entities;
using GNFSRS.Domain.Concrete;
using GNFSRS.Domain.Abstract;
using GNFSRS.WebUI.Models;
using GNFSRS.Domain.JQueryDataTable;

namespace GNFSRS.WebUI.Controllers
{
    public class AfterReportController : Controller
    {
        private IAfterReportRepository db;

        public AfterReportController(IAfterReportRepository repo)
        {
            db = repo;
        }

        //
        // GET: /AfterReport/

        //public ActionResult Index()
        //{
        //    ViewBag.duration = db.Duration_Of_Event("CodeE111");
        //    return View(db.AfterReports.ToList());
        //}


        [HttpGet]
        public ActionResult Search()
        {
            return View("Search");
        }

        [HttpPost]
        public JsonResult Search(JQueryDataTablesModel jQueryDataTablesModel)
        {
            int totalRecordCount;
            int searchRecordCount;
            var beforeReports = db.GetAfterReports(
                startIndex: jQueryDataTablesModel.iDisplayStart,
                pageSize: jQueryDataTablesModel.iDisplayLength,
                sortedColumns: jQueryDataTablesModel.GetSortedColumns(),
                totalRecordCount: out totalRecordCount,
                searchRecordCount: out searchRecordCount,
                searchString: jQueryDataTablesModel.sSearch);

            return Json(new { items = beforeReports, totalRecords = totalRecordCount, totalDisplayRecords = totalRecordCount, sEcho = 1 });


        }

        //
        // GET: /BeforeReports/Index/
        [Authorize]
        public ActionResult Index(string sort, string cT, string cO, string sT, string sO, int? page)
        {
            // Test duration methods
            ViewBag.duration = db.Duration_Of_Event("CodeE111");

            ViewBag.ReportCodeSortParam = string.IsNullOrEmpty(sort) ? "report_Code_desc" : "";
            ViewBag.ReportDateSortParam = sort == "status" ? "status_desc" : "status";

            if (Request != null)
            {
                if (Request.HttpMethod == "GET")
                {
                    sT = cT;
                    sO = cO;
                }
                else
                {
                    page = 1;
                }
            }

            ViewBag.ShortInfoText = sT;
            ViewBag.OtherDetailsText = sO;

            IQueryable<AfterReport> after_reports = db.AfterReports;

            if (!string.IsNullOrEmpty(sT))
            {
                after_reports = after_reports.Where(e => e.cause_of_fire.ToUpper().Contains(sT.ToUpper()) ||
                     e.report_Code.ToUpper().Contains(sT.ToUpper()));
            }

            if (!string.IsNullOrEmpty(sO))
            {
                //// ***************************************************
                //// Developer Nightmare encounterd
                //// Linq cannot interpret DateTime object,
                //// Thus must convert input to DateTime 
                //// Before using in linq expression.
                //// ****************************************************
                //if (sO.Length > 5)
                //{
                //    var sDate = DateTime.Parse(sO);
                //    after_reports = after_reports.Where(e => e.before_ReportDate == sDate);
                //    //ViewBag.Date = sDate;
                //}
                //else
                //{
                //    // Convert string to DateTime Year if length < 5
                //    var sDate = DateTime.ParseExact(sO, "yyyy", null);


                // Search by status
                after_reports = after_reports.Where(e => e.status.ToLower().Trim() == sO.ToLower().Trim());

              

                // before_reports = before_reports.Where(e => e.before_ReportDate == ViewBag.Date); //.ToString().ToUpper().Contains(sO.ToUpper())
            }

            switch (sort)
            {
                case "report_Code_desc":
                    after_reports = after_reports.OrderByDescending(e => e.report_Code);
                    break;
                case "status":
                    after_reports = after_reports.OrderBy(e => e.status);
                    break;
                case "status_desc":
                    after_reports = after_reports.OrderByDescending(e => e.status);
                    break;
                default:
                    after_reports = after_reports.OrderBy(e => e.report_Code);
                    break;
            }

            int pageSize = 2;
            int pageNumber = (page ?? 1);

            return View(after_reports.ToPagedList(pageNumber, pageSize));
        }


        //
        // GET: /AfterReport/Details/5

        public ActionResult Details(int id = 0)
        {
            AfterReport afterreport = db.GetAfterReport(id);
            if (afterreport == null)
            {
                return HttpNotFound();
            }
            return View(afterreport);
        }

        //
        // GET: /AfterReport/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /AfterReport/Create

        [HttpPost]
        public ActionResult Create(AfterReport afterreport)
        {
            if (ModelState.IsValid)
            {

                db.Save_After_Report(afterreport);
                return RedirectToAction("Index");
            }

            return View(afterreport);
        }

        //
        // GET: /AfterReport/Edit/5

        public ActionResult Edit(int id = 0)
        {
            AfterReport afterreport = db.GetAfterReport(id);
            if (afterreport == null)
            {
                return HttpNotFound();
            }
            return View(afterreport);
        }

        //
        // POST: /AfterReport/Edit/5

        [HttpPost]
        public ActionResult Edit(AfterReport afterreport)
        {
            if (ModelState.IsValid)
            {

                db.Save_After_Report(afterreport);
                return RedirectToAction("Index");
            }
            return View(afterreport);
        }

        //
        // GET: /AfterReport/Delete/5

        public ActionResult Delete(int id = 0)
        {
            AfterReport afterreport = db.GetAfterReport(id);
            if (afterreport == null)
            {
                return HttpNotFound();
            }
            return View(afterreport);
        }

        //
        // POST: /AfterReport/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
           
            db.Delete_After_Report(id);
            return RedirectToAction("Index");
        }


        //
        //AJAX GET:
        public JsonResult GetBeforeReportShortInfo(int id)
        {
            AfterReport afReport = db.GetAfterReport(id);
            if (afReport == null)
            {
                return Json(new
                {
                    report_Code = "Not Found",
                    satus = "Not Found",
                    cause_of_fire = "Not Found",
                    //reportDate = "Not Found",
                });
            }
            return Json(new
            {
                report_Code = afReport.report_Code,
                satus = afReport.status,
                cause_of_fire = afReport.cause_of_fire,
                //reportComments = afReport.before_Report_Comments
            }, JsonRequestBehavior.AllowGet);

        }

        //
        //AJAX GET:
        public JsonResult GetMatchingAfterReports(string term)
        {
            var result = (from e in db.AfterReports
                          orderby e.after_ReportID
                          where e.report_Code.StartsWith(term)
                          select new { AfterReportID = e.after_ReportID, ReportCode = e.report_Code })
                          .Take(15).ToList();
            return Json(result, JsonRequestBehavior.AllowGet);
        }


        //protected override void Dispose(bool disposing)
        //{
        //    db.Dispose();
        //    base.Dispose(disposing);
        //}
    }
}

GNFSRS.WebUI/Controllers/AuditController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GNFSRS.WebUI.Filters;
using GNFSRS.Domain.Entities;
using GNFSRS.Domain.Concrete;

namespace GNFSRS.WebUI.Controllers
{
    [Authorize]
    public class AuditController : Controller
    {
        private EFDbContext db = new EFDbContext();

        //
        // GET: /Audit/

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult AuditRecords()
        {
            var audits = db.AuditRecords.OrderBy(a => a.TimeAccessed);
            return View(audits);
        }

        public ActionResult Details(int id)
        {
            Audit audit = db.AuditRecords.Find(id);
            if (audit == null)
            {
                return View("NotFound");
            }
            return View(audit);
        }
    }
}

GNFSRS.WebUI/Views/Shared/BeforeReportSummary.cshtml
@model GNFSRS.Domain.Entities.BeforeReport

<table>
   
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.report_Code)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.before_ReportDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.before_ReportTime)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.before_Venue)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.before_Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.before_Phone)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.tender_Depature_Time)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.before_Report_Comments)
        </th>
        <th></th>
    </tr>
    

@foreach (var item in Model as IEnumerable<GNFSRS.Domain.Entities.BeforeReport>) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.report_Code)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.before_ReportDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.before_ReportTime)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.before_Venue)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.before_Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.before_Phone)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.tender_Depature_Time)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.before_Report_Comments)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.before_ReportID }) |
            @Html.ActionLink("Details", "Details", new { id=item.before_ReportID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.before_ReportID })
        </td>
    </tr>
}

</table>

GNFSRS.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>@ViewBag.Title - My ASP.NET MVC Application</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta name="viewport" content="width=device-width" />
        <link href="~/Content/post.css" type="text/css" rel="stylesheet" />
        <link href="~/Content/box.css" type="text/css" rel="stylesheet" />
        <link href="~/Content/PagedList.css" type="text/css" rel="stylesheet" />
        <link href="~/Content/tablestyle.css" type="text/css" rel="stylesheet" />
        @RenderSection("header", required: false)
                
        @Styles.Render("~/Content/css")
        @*@Scripts.Render("~/bundles/modernizr")*@
    </head>
    <body>
        <header>
            <div class="content-wrapper">
                <div class="float-left">
                    <p class="site-title">@Html.ActionLink("your logo here", "Index", "Home")</p>
                </div>
                <div class="float-right">
                    <section id="login">
                        @Html.Partial("_LoginPartial")
                    </section>
                    <nav>
                        <ul id="menu">
                            <li>@Html.ActionLink("Home", "Index", "Home")</li>
                            <li>@Html.ActionLink("About", "About", "Home")</li>
                            <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                            <li>@Html.ActionLink("Before Reports", "Index", "BeforeReport")</li>
                            <li>@Html.ActionLink("After Reports", "Index", "AfterReport")</li>
                            <li>@Html.ActionLink("Archives", "Index", "Archives")</li>
                            <li>@Html.ActionLink("Generate Reports", "Index", "GenerateReports")</li>
                             <li>@Html.ActionLink("Session Activities","AuditRecords","Audit")</li>
                        </ul>
                    </nav>
                </div>
            </div>
        </header>
        <div id="body">
            @RenderSection("featured", required: false)
            <section class="content-wrapper main-content clear-fix">
                @RenderBody()
            </section>
        </div>
        <footer>
            <div class="content-wrapper">
                <div class="float-left">
                    <p>&copy; @DateTime.Now.Year - My ASP.NET MVC Application</p>
                </div>
            </div>
        </footer>

        @*@Scripts.Render("~/bundles/jquery")*@
        <script src="@Url.Content("~/Scripts/jquery-1.5.1.min.js")"></script>
        <script src="@Url.Content("~/Scripts/modernizr-1.7.min.js")"></script>
        @RenderSection("scripts", required: false)
    </body>
</html>