GNFSRS.WebUI/Models/EventImageViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace GNFSRS.WebUI.Models
{
    public class EventImageViewModel
    {
        public EventImageViewModel()
        {
            Images = new List<string>();
        }

        public List<string> Images { get; set; }

        [Required(ErrorMessage="Report Code needed")]
        [Display(Name = "Report Code")]
        public string report_Code { get; set; }

        public string image_path { get; set; }

        [Display(Name = "Local file")]
        public HttpPostedFileBase File { get; set; }

        public bool IsFile { get; set; }

        [Range(0, int.MaxValue)]
        public int X { get; set; }

        [Range(0, int.MaxValue)]
        public int Y { get; set; }

        [Range(1, int.MaxValue)]
        public int Width { get; set; }

        [Range(1, int.MaxValue)]
        public int Height { get; set; }
    }
}

GNFSRS.WebUI/Controllers/EventImagesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GNFSRS.Domain.Entities;
using GNFSRS.Domain.Concrete;
using GNFSRS.Domain.Abstract;
using GNFSRS.WebUI.Models;
using System.Drawing;
using System.IO;
using System.Drawing.Drawing2D;
using System.Net;

namespace GNFSRS.WebUI.Controllers
{
    public class EventImagesController : Controller
    {
        private IEventImagesRepository db;

        public EventImagesController(IEventImagesRepository repo)
        {
            db = repo;
        }

        //
        // GET: /EventImages/

        public ActionResult Index()
        {
            var images = new EventImageViewModel();
            //Read out files from the files directory
            var files = Directory.GetFiles(Server.MapPath("~/Content/img"));
            //Add them to the model
            foreach (var file in files)
                images.Images.Add(Path.GetFileName(file));

            return View(images);
        }


        public ActionResult GetImageForEvent(string reportCode = null)
        {
            var eventImages = new EventImageViewModel();
            var eventImagesFiles = Directory.GetFiles(Server.MapPath("~/Content/img"));

            foreach (var file in eventImagesFiles)
            {
                if (reportCode != null)
                {
                    if (file.Contains(reportCode) == true)
                    {
                        eventImages.Images.Add(Path.GetFileName(file));
                    }
                }
              
            }

            return View(eventImages);
        }

        //
        // POST: /Home/PreviewImage

        [HttpPost]
        public ActionResult PreviewImage()
        {
            var bytes = new byte[0];
            ViewBag.Mime = "image/png";

            if (Request.Files.Count == 1)
            {
                bytes = new byte[Request.Files[0].ContentLength];
                Request.Files[0].InputStream.Read(bytes, 0, bytes.Length);
                ViewBag.Mime = Request.Files[0].ContentType;
            }

            ViewBag.Message = Convert.ToBase64String(bytes, Base64FormattingOptions.InsertLineBreaks);
            return PartialView();
        }

        //
        // GET: /Home/UploadImageModal

        public ActionResult UploadImageModal()
        {
            return View();
        }

     
        //
        // GET: /EventImages/Delete/5

        public ActionResult Delete(int id = 0)
        {
            EventImage eventimage = db.GetEventImages(id);
            if (eventimage == null)
            {
                return HttpNotFound();
            }
            return View(eventimage);
        }

        //
        // POST: /EventImages/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            
            db.Delete_Image_Path(id);
            return RedirectToAction("Index");
        }




        public ActionResult UploadImage()
        {
            //Just to distinguish between ajax request (for: modal dialog) and normal request
            if (Request.IsAjaxRequest())
            {
                return PartialView();
            }

            return View();
        }

        //
        // POST: /Home/UploadImage

        [HttpPost]
        public ActionResult UploadImage(EventImageViewModel model)
        {
            EventImage eventImage = new EventImage();

            //Check if all simple data annotations are valid
            if (ModelState.IsValid)
            {
                //Prepare the needed variables
                Bitmap original = null;
                var name = "newimagefile";
                var errorField = string.Empty;

               
                if (model.File != null) // model.IsFile
                {
                    errorField = "File";
                    name = Path.GetFileNameWithoutExtension(model.File.FileName);
                    original = Bitmap.FromStream(model.File.InputStream) as Bitmap;
                }

                //If we had success so far
                if (original != null)
                {
                    var img = CreateImage(original, model.X, model.Y, model.Width, model.Height);

                    // Save image in the file system
                    var fn = Server.MapPath("~/Content/img/"+ model.report_Code+ "-" + name + ".png");

                    //******************* Store Image Path in DB **********************//
                    eventImage.image_path = fn;
                    eventImage.report_Code = model.report_Code;
                    db.Save_Image_Path(eventImage);
                    // *****************************************************************//

                    // Flush Image to folder
                    img.Save(fn, System.Drawing.Imaging.ImageFormat.Png);

                    ViewBag.Success = "The Image has been uploaded successfully....";
                    return View();
                }
                else //Otherwise we add an error and return to the (previous) view with the model data
                    ModelState.AddModelError(errorField, "Your upload did not seem valid. Please try again using only correct images!");
                    ViewBag.Error = "Your upload did not seem valid. Please try again using only correct images!";
            }

            ViewBag.Error = "Your upload did not seem valid. Please try again using only correct images! and Enter Report Code";
            return View(model);
        }

        /// <summary>
        /// Creates a small image out of a larger image.
        /// </summary>
        /// <param name="original">The original image which should be cropped (will remain untouched).</param>
        /// <param name="x">The value where to start on the x axis.</param>
        /// <param name="y">The value where to start on the y axis.</param>
        /// <param name="width">The width of the final image.</param>
        /// <param name="height">The height of the final image.</param>
        /// <returns>The cropped image.</returns>
        Bitmap CreateImage(Bitmap original, int x, int y, int width, int height)
        {
            var img = new Bitmap(width, height);

            using (var g = Graphics.FromImage(img))
            {
                g.SmoothingMode = SmoothingMode.AntiAlias;
                g.InterpolationMode = InterpolationMode.HighQualityBicubic;
                g.DrawImage(original, new Rectangle(0, 0, width, height), x, y, width, height, GraphicsUnit.Pixel);
            }

            return img;
        }

      
    }
}

GNFSRS.WebUI/Views/EventImages/Delete.cshtml
@model GNFSRS.Domain.Entities.EventImage

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>EventImage</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.report_Code)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.report_Code)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.image_path)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.image_path)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

GNFSRS.WebUI/Views/EventImages/GetImageForEvent.cshtml
@model GNFSRS.WebUI.Models.EventImageViewModel

@{
    Layout = null;
  }

@if (Model.Images.Count > 0)
{
<div class="imageContainer">
@foreach (var src in Model.Images)
{
    <div class="imageBox">
        <a href="@Url.Content("~/Content/img/" + src)" target="_blank"><img src="@Url.Content("~/Content/img/" + src)" alt="Image" class="imagePreview" /></a>
    </div>
}
</div>
}
else
{
<div class="imageCenter">
    No images have been uploaded so far. @Html.ActionLink("Click here", "UploadImage") to upload an image.
</div>
}
<div class="clear"></div>

GNFSRS.WebUI/Views/EventImages/Index.cshtml
@model GNFSRS.WebUI.Models.EventImageViewModel

@{
    ViewBag.Title = "Index";
}

<h2>Events Images</h2>

<p>
    @Html.ActionLink("Upload New Images", "UploadImage")
</p>

@if (Model.Images.Count > 0)
{
<div class="imageContainer">
@foreach (var src in Model.Images)
{
    <div class="imageBox">
        <a href="@Url.Content("~/Content/img/" + src)" target="_blank"><img src="@Url.Content("~/Content/img/" + src)" alt="Image" class="imagePreview" /></a>
    </div>
}
</div>
}
else
{
<div class="imageCenter">
    No images have been uploaded so far. @Html.ActionLink("Click here", "UploadImage") to upload an image.
</div>
}
<div class="clear"></div>

GNFSRS.WebUI/Views/EventImages/PreviewImage.cshtml
<img src="data:@ViewBag.Mime;base64,@ViewBag.Message" />

GNFSRS.WebUI/Views/EventImages/UploadImage.cshtml
@model GNFSRS.WebUI.Models.EventImageViewModel

@{
    ViewBag.Title = "UploadImage";
  
}
<link href="@Url.Content("~/Content/ImageArea.css")" rel="stylesheet" />
@section Scripts
{
<script src="@Url.Content("~/Scripts/jquery.validate.min.js")"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")"></script>
<script src="@Url.Content("~/Scripts/jquery.imgareaselect.js")"></script>
<script src="@Url.Content("~/Scripts/jquery.fancyupload.js")"></script>
<script>
    $(document).ready(function () {
        initSelect();
    });
</script>
}
<h2>Upload an image</h2>
<p style="color:green; font-size:large; font-family:'Blackadder ITC'">
    @ViewBag.Success
</p>
<p style="color:red; font-size:large; font-family:'Blackadder ITC'">
     @ViewBag.Error
    </p>
@using (Html.BeginForm("UploadImage", "EventImages", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
     @Html.ValidationSummary(true)

    @Html.HiddenFor(model => model.X)
    @Html.HiddenFor(model => model.Y)
    @Html.HiddenFor(model => model.Width)
    @Html.HiddenFor(model => model.Height)
    <div id="upload-choices">
       
        <div class="editor-row">
            <div class="editor-label">
                @Html.LabelFor(model => model.report_Code)
                </div>
            </div><div class="editor-field">
                 @Html.EditorFor(model => model.report_Code)
                 @Html.ValidationMessageFor(model => model.File)
                </div>

            <div class="editor-label">
                @Html.EditorFor(model => model.IsFile)
                @Html.LabelFor(model => model.File)
            </div><div class="editor-field">
                @Html.FileFor(model => model.File)
                @Html.ValidationMessageFor(model => model.File)
            </div>
        </div>
      
   
    <div id="upload-cut">
        <img alt="Field for image cutting" id="preview" src="@Url.Content("~/Content/empty.png")" />
    </div>
    <div class="clear">
        <button type="submit">Upload</button>
    </div>
}

GNFSRS.WebUI/Views/EventImages/UploadImageModal.cshtml
@{
    Layout = null;
}


<link href="@Url.Content("~/Content/Modal.css")" rel="stylesheet" />
<link href="@Url.Content("~/Content/ImageArea.css")" rel="stylesheet" />

@section Scripts
{
<script src="@Url.Content("~/Scripts/jquery.validate.min.js")"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")"></script>
<script src="@Url.Content("~/Scripts/jquery.imgareaselect.js")"></script>
<script src="@Url.Content("~/Scripts/jquery.fancyupload.js")"></script>
<script>
    $(document).ready(function () {
        $('.modal_block').click(function (e) {
            $('#tn_select').empty();
            $('.modal_part').hide();
        });
        $('#modal_link').click(function (e) {
            $('.modal_part').show();
            var context = $('#tn_select').load('~/Views/EventImages/UploadImage', function () {
                initSelect(context);
            });
            e.preventDefault();
            return false;
        });
    });
</script>
}
<div class="modal_block modal_part"></div>
<div class="modal_dialog modal_part" id="tn_select"></div>
<h2>Upload an image by using a modal dialog</h2>
<p>
    This is a sample page with basically no content (but there could be one!). Now we will just
    upload content as on the @Html.ActionLink("Upload Image page", "UploadImage", "EventImages"). The only
    difference lies in the usage of a modal dialog to upload the actual image.
</p>
<p>
    <a href="#" id="modal_link">Click here to open modal dialog.</a>
</p>